### ISSUE TITLE
Craft 4 Support

### ISSUE THREAD

**Issue by icreatestuff** [clubstudioltd/craft-inline-svg#3]
Hello, will this plugin be updated to support Craft 4? Many thanks.

![Screenshot 2022-05-12 at 10 02 00](https://user-images.githubusercontent.com/1300714/168034008-e3dc678f-2092-4737-92ae-ab891245f0f3.png)

**Comment by scottwakefield** [comment]
Hi @icreatestuff,

We plan to update it in a week or so. I'll let you know when we tag the new release.

**Comment by scottwakefield** [comment]
Hi @icreatestuff,

We just tagged v2.0.0, which brings compatibility with Craft 4. Take it for a spin and let us know if you hit any issues!

👍
