### ISSUE TITLE
Craft CMS 5 support

### ISSUE THREAD

**Issue by cbovers** [clubstudioltd/craft-inline-svg#4]
Hello, will there be Craft CMS 5 support for this plugin?

`clubstudioltd/craft-inline-svg[dev-master, 2.0.0] require craftcms/cms ^4.0.0 -> found craftcms/cms[4.0.0-alpha.1, ..., 4.x-dev] but it conflicts with your root composer.json require (^5.0.0-beta.6)`

**Comment by scottwakefield** [comment]
Hi @cbovers,

Yep, we'll get this updated for Craft 5. It'll likely be within the next week or so 👍🏻

**Comment by scottwakefield** [comment]
Hey @cbovers,

I've just tagged a new release with Craft 5 compatibility 👍🏻
